Repository typed-ember/ember-cli-typescript, pull requests merged in 2022-10, with the labels that each got.

#1531 Fix types in CI by updating lockfile
  package.json
  yarn.lock
Labels: dependencies

#1526 Include `@types/ember__destroyable` when running the default blueprint
  ts/blueprints/ember-cli-typescript/index.js
Labels: enhancement

#1534 Use volta action v4 for all targets
  .github/workflows/ci.yml
Labels: ci, internal

#1535 Fix tests on current Ember CLI
  package.json
  ts/tests/acceptance/build-test.ts
  yarn.lock
Labels: internal

#1537 Airlift `updatePathsForAddon` from the blueprints package
  docs/configuration.md
  docs/ts/with-addons.md
  package.json
  ts/blueprints/ember-cli-typescript/index.js
  ts/blueprints/ember-cli-typescript/update-paths-for-addon.js
  yarn.lock
Labels: bug

#1536 Set up release-it for publishing
  .eslintrc.js
  package.json
  test-fixtures/skeleton-app/tsconfig.json
  ts/addon.ts
  ts/tests/acceptance/build-test.mts
  ts/tests/helpers/skeleton-app.mts
  ts/tests/unit/copy-declarations-test.ts
  ts/tsconfig.json
  ts/types/fixturify/index.d.ts
  tsconfig.json
  yarn.lock
Labels: internal
